<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1 charset=utf-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="../css/index.css">
</head>
<body>
    <div class="container-fluid">
        <div id="activate" class="col-lg-4 col-lg-offset-4">
            <p>Čestitamo, aktivirali ste vaš korisnički račun!</p>
            <a href="../index.php">Povratak na prijavu</a>
        </div>
        
    </div>
</body>
</html>
