<form method='post' class='addActivityForm'>
    <input class="form-control activity" name="activity" type="text">
    <button type="button" class="btn btn-default addActivity" disabled>Postavi</button>
    <div class="form-group messageActivity">
    </div>
</form>
<table class="table table-condensed table-bordered table-hover" id="activityList">
    <thead>
        <tr>            
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
