<div class="row directions" id="directions">
    <div class="col-lg-8 col-lg-offset-2">
        <h2 class="title">Upute</h2>
            <div id="upute">
                <ul>
                    <li>Odabrati uslugu</li>
                    <li>Nakon odabrane usluge, odaberite datum usluge</li>
                    <li>Nakon odabranog datuma, odaberite termin usluge</li>
                    <li>Nakon odabranog termina, odaberite trajanje usluge</li>
                    <li>Sačekajte potvrdu usluge od admin-a</li>
                    <li>Ukoliko je admin potvrdio termin usluge, na Vaš e-mail je stigla potvrda te informacije o usluzi</li>
                </ul>
                <h4>Morate ići ovim redoslijedom jer su select box-ovi onemogućeni!</h4>
            </div>
    </div>
</div>
<hr>

