<footer>
    <div class="row kontakt">
        <div class="col-lg-4 col-lg-offset-4">
            <h4>Kontakt</h4>
            <h5>Šimun Gogić</h5>
            <h5>J.J.Strossmayera 224a, Osijek</h5>
            <h5>099 272 1993</h5>
            <h5>simun.gogic@gmail.com</h5> 
        </div>
    </div>
    <div class="row prava">
        <div class="col-lg-4 col-lg-offset-4">
            <h5>© 2017 / Sva prava pridržana - Gogić</h5>
        </div>
    </div>
</footer> 
