<div class="row header">
    <div class="col-lg-1 menu" data-spy="affix" data-offset-top="197">
        <a type="button" href="#lista" class="btn-lg btn btn-default">Lista čekanja</a>
        <a type="button" href="#radno" class="btn-lg btn btn-default">Radno vrijeme</a>
        <a type="button" href="#usluge" class="btn-lg btn btn-default">Usluge</a>
        <a type="button" href="#kalendar" class="btn-lg btn btn-default">Kalendar</a>
        <a type="button" href="logic/logout.php" class="btn-lg btn btn-default logout">Odjava</a>
    </div>
    <div class="col-lg-6 col-lg-offset-2">
        <h2 class="descr">Booking App</h2>
        <h3 class="descr"><q>Rezervirajte termin za vašu omiljenu aktivnost iz udobnosti fotelje.</q></h3>
        <br>
        <h2 class="descr" style="text-transform: uppercase">Admin Panel</h2>
    </div>
</div>
