<nav class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Booking</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="#">LISTA ČEKANJA</a></li>
      <li><a href="#">POSTAVI RADNO VRIJEME</a></li>
      <li><a href="#">DODAJ USLUGU</a></li>
      <li><a href="#">KALENDAR</a></li>
      <li><a href="#">O APLIKACIJI</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="logic/logout.php">Odjavi se</a></li>
    </ul>
</nav>
