<div class="row header">
    <div class="col-lg-1 menu" data-spy="affix" data-offset-top="197">
        <a type="button" href="#directions" class="btn-lg btn btn-default upute">Upute</a>
        <a type="button" href="#userForm" class="btn-lg btn btn-default omeni">Naruči se</a>
        <a type="button" href="logic/logout.php" class="btn-lg btn btn-default logout">Odjava</a>
    </div>
    <div class="col-lg-6 col-lg-offset-2">
        <h2 class="descr">Booking App</h2>
        <h3 class="descr"><q>Rezervirajte termin za vašu omiljenu aktivnost iz udobnosti fotelje.</q></h3>
    </div>
</div>


