<div id="nav" class="overlay">

<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
<div class="overlay-content">
<a href="#about">O APLIKACIJI</a>
<a href="#directions">UPUTE</a>
<a href="#">NARUČI SE</a>
<a href="logic/logout.php">ODJAVI SE</a>
  </div>
</div>
<div class="track" style="position: fixed;">
    <span style="font-size:30px;cursor:pointer; position:absolute; left: 50%; top: 50%; transform: translate(-50%, -50%);
          " onclick="openNav()">&#9776;</span>
</div>


