<form method='post' class='loginForm'>
    <div class="input-group emailLogin btn-block">                                                                                            
        <input type="text" class="form-control input-lg emailLogin" data-toggle="tooltip"
               name="emailLogin" placeholder="Unesi Email" id="email"> 
    </div>
    <div class="input-group passwordLogin btn-block">                                                                                             
        <input type="password" class="form-control input-lg passwordLogin" data-toggle="tooltip"
               name="passwordLogin" placeholder="Unesi Lozinku" id="password">                                 
    </div> 
    <div class="input-group btn-block">
        <input type="button" class="btn btn-default login btn-lg btn-block" value="Login">                   
        <button  type="button" class="btn btn-link btn-block" data-toggle="modal" data-target=".modal">Niste registrirani?                                               
        </button>                    
    </div> 
</form>


