<form method='post' class='loginForm'>
    <div class="input-group emailLogin">                                                                                            
        <input type="text" class="form-control input-lg" name="emailLogin" placeholder="Unesi Email" id="email"> 
    </div>
    <div class="input-group passwordLogin">                                                                                             
        <input type="password" class="form-control input-lg" name="passwordLogin" placeholder="Unesi Lozinku" id="password">                                 
    </div> 
    <div class="form-group">
        <input type="button" class="btn btn-default login input-lg" value="Login">                   
        <button  type="button" class="btn btn-link" data-toggle="modal" data-target=".modal">Niste registrirani?                                               
        </button>                    
    </div> 
    <div class="input-group messageLogin">
    </div>
</form>

