<form method='post' class='registerForm'>
    <div class="modal fade-scale" role="dialog" data-backdrop="static" data-keyboard="false">  
        <div class="modal-dialog">    
            <div class="modal-content">      
                <div class="modal-header">        
                    <button type="button" class="close" data-dismiss="modal">&times;
                    </button>        
                    <h4 class="modal-title text-center">Registracija korisnika</h4>      
                </div>        
                <div class="modal-body">
                    <div class="form-group">
                        <input type="text" class="form-control name" name="name" data-toggle="tooltip" placeholder="Ime i prezime"> 
                    </div>    
                    <div class="form-group">
                        <input type="text" class="form-control oib" name="oib" data-toggle="tooltip" placeholder="OIB"> 
                    </div> 
                    <div class="form-group">    
                        <input type="password" class="form-control password" data-toggle="tooltip" name="password" placeholder="Lozinka">  
                    </div>  
                    <div class="form-group">    
                        <input type="password" class="form-control passwordRepeat" data-toggle="tooltip" name="passwordRepeat" placeholder="Ponovi lozinku">      
                    </div>
                    <div class="form-group">
                        <input type="email" class="form-control email" name="email" data-toggle="tooltip" placeholder="Email"> 
                    </div> 
                    <div class="form-group">
                        <input type="button" class="btn btn-lg btn-default register btn-block" value="Registriraj se" >  
                    </div> 
                    <div class="form-group">
                        <div class="message"></div>
                    </div>
                </div> 
            </div>    
        </div>  
    </div>
</form>
