<form method='post' class='registerForm'>
    <div class="modal fade-scale" role="dialog" data-backdrop="static" data-keyboard="false">  
        <div class="modal-dialog">    
            <div class="modal-content">      
                <div class="modal-header">        
                    <button type="button" class="close" data-dismiss="modal">&times;
                    </button>        
                    <h4 class="modal-title text-center">Registracija korisnika</h4>      
                </div>        
                <div class="modal-body">
                    <div class="form-group name">
                        <input type="text" class="form-control" name="name" placeholder="Ime i prezime"> 
                    </div>    
                    <div class="form-group oib">
                        <input type="text" class="form-control" name="oib" placeholder="OIB"> 
                    </div> 
                    <div class="form-group password">    
                        <input type="password" class="form-control" name="password" placeholder="Lozinka">  
                    </div>  
                    <div class="form-group passwordRepeat">    
                        <input type="password" class="form-control" name="passwordRepeat" placeholder="Ponovi lozinku">      
                    </div>
                    <div class="form-group email">
                        <input type="email" class="form-control" name="email" placeholder="Email"> 
                    </div> 
                    <div class="form-group register">
                        <input type="button" class="btn btn-default register" value="Registriraj se" >  
                    </div> 
                    <div class="form-group message">
                    </div>
                </div> 
            </div>    
        </div>  
    </div>
</form>
