<form method='post' class='userForm'>
    <select class="form-control activity" name="activity" type="text">
        <option disabled selected value> -- odaberite aktivnost -- </option>
    </select>
    <input class="form-control datePicker" name="datePicker" type="text" disabled readonly="true">
    <input class="form-control actualDate hidden" name="actualDate" type="text">
    <button type="button" class="btn btn-default clickTimePicker" disabled>Odaberi termin</button>
    <input class="form-control timePicker" name="timePicker" type="text" disabled>
    <select class="form-control duration" name="duration" type="text" disabled>
        <option disabled selected value> -- odaberite trajanje -- </option>
        <option value="30" class="29">00:30</option>
        <option value="60" class="59">01:00</option>
        <option value="90" class="89">01:30</option>
        <option value="120" class="119">02:00</option>
    </select>
    <button type="button" class="btn btn-default set" disabled>Naruči se</button>
    <div class="form-group messageOptions">
    </div>
</form>


