<form method='post' class='workingTimeForm'>
    <button type="button" class="btn btn-default clickTimePickerStart">Početak radnog vremena</button>
    <input class="form-control timePickerStart" name="timePickerStart" type="text" disabled>
    <button type="button" class="btn btn-default clickTimePickerEnd" disabled>Kraj radnog vremena</button>
    <input class="form-control timePickerEnd" name="timePickerEnd" type="text" disabled>
    <button type="button" class="btn btn-default setWorkingTime" disabled>Postavi</button>
    <div class="form-group messageWorkingTime">
    </div>
</form>


